name: 'Run staticcheck with reviewdog'
description: '🐶 Run staticcheck with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-check,github-pr-review].'
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for staticcheck ###
  target:
    description: 'Target of staticcheck'
    default: './...'
  staticcheck_flags:
    description: 'staticcheck flags'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.18.1
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: '${{ inputs.github_token }}'
        INPUT_WORKDIR: '${{ inputs.workdir }}'
        INPUT_LEVEL: '${{ inputs.level }}'
        INPUT_FAIL_ON_ERROR: '${{ inputs.fail_on_error }}'
        INPUT_FILTER_MODE: '${{ inputs.filter_mode }}'
        INPUT_REPORTER: '${{ inputs.reporter }}'
        INPUT_REVIEWDOG_FLAGS: '${{ inputs.reviewdog_flags }}'
        INPUT_TARGET: '${{ inputs.target }}'
        INPUT_STATICCHECK_FLAGS: '${{ inputs.staticcheck_flags }}'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check'
  color: 'blue'
