name: 'Run staticcheck with reviewdog'
description: '🐶 Run staticcheck with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-check,github-pr-review].'
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_level:
    description: |
      If set to `none`, always use exit code 0 for reviewdog. Otherwise, exit code 1 for reviewdog if it finds at least 1 issue with severity greater than or equal to the given level.
      Possible values: [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: |
      Deprecated, use `fail_level` instead.
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
    deprecationMessage: 'Deprecated, use `fail_level` instead.'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  ### Flags for staticcheck ###
  target:
    description: 'Target of staticcheck'
    default: './...'
  staticcheck_flags:
    description: 'staticcheck flags'
    default: ''
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
      with:
        reviewdog_version: v0.20.3
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: '${{ inputs.github_token }}'
        INPUT_WORKDIR: '${{ inputs.workdir }}'
        INPUT_LEVEL: '${{ inputs.level }}'
        INPUT_FAIL_LEVEL: ${{ inputs.fail_level }}
        INPUT_FAIL_ON_ERROR: '${{ inputs.fail_on_error }}'
        INPUT_FILTER_MODE: '${{ inputs.filter_mode }}'
        INPUT_REPORTER: '${{ inputs.reporter }}'
        INPUT_REVIEWDOG_FLAGS: '${{ inputs.reviewdog_flags }}'
        INPUT_TARGET: '${{ inputs.target }}'
        INPUT_STATICCHECK_FLAGS: '${{ inputs.staticcheck_flags }}'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check'
  color: 'blue'
