name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test-check:
    name: runner / staticcheck (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "testdata/go.mod"
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          target: ./testdata/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / staticcheck (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "testdata/go.mod"
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          workdir: ./testdata
          reviewdog_flags: -filter-mode=file

  test-go-install:
    name: runner / staticcheck (use_go_install)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "testdata/go.mod"
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          workdir: ./testdata
          use_go_install: true
